version: "3.3"
# Este es un archivo de docker-compose.yml para configurar el uso de contenedores de software.

services:

  django_dev:
    # build es el lugar desde donde toma los archivos para generar la imagen.
    build: .
    # Imágen a utilizar:
    image: django_dev
    # Nombre del container:
    container_name: django_dev
    # Comportamiento ante fallos y al iniciar el sistema:
    restart: always
    # Carpetas enlazadas:
    volumes:
      # Source code directory:
      - type: bind
        source: .
        target: /opt/back_end
    # Puertos enlazados:
    ports:
        - "8000:8000"
    # Control de consola:
    stdin_open: true
    tty: true
    # Se ejecuta comando utilizando bash:
    command: bash -c "mkdir -p powermeter/database && python powermeter/manage.py runserver 0.0.0.0:8000"