# Generated by Django 3.2.2 on 2021-12-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementModel',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0, verbose_name='value')),
                ('date', models.CharField(default='dd-mm-yyyy hh:mm:ss', max_length=40, verbose_name='date')),
            ],
            options={
                'db_table': 'sensor_data_measurements',
            },
        ),
    ]
