# Generated by Django 3.2.2 on 2021-12-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_rename_measurementmodel_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='time',
            field=models.CharField(default='hh:mm:ss', max_length=40, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.CharField(default='dd-mm-yyyy', max_length=40, verbose_name='date'),
        ),
    ]
